src/prometheus_alert_rules/mega_raid.yaml
tests/unit/test_alert_rules/test_mega_raid.yaml

Add the following alert rules for MegaRAID controller.
- StorcliCommandFailed
- MegaRAIDControllerNotFound
- MegaRAIDVirtualDriveNotOptimal
Tested with `promtool`
```yaml
rule_files:
- ../../../src/prometheus_alert_rules/mega_raid.yaml
evaluation_interval: 1m
tests:
- interval: 1m
input_series:
- series: 'storcli_command_success{instance="ubuntu-0"}'
values: '0x15' # error
- series: 'storcli_command_success{instance="ubuntu-1"}'
values: '1x15'
- series: 'megaraid_controllers{instance="ubuntu-1", hostname="ubuntu-1"}'
values: '0x15' # error
- series: 'megaraid_virtual_drive_state{instance="ubuntu-1", controller_id="0", virtual_drive_id="239", state="Optl"}'
values: '1x15' # okay
- series: 'megaraid_virtual_drive_state{instance="ubuntu-1", controller_id="0", virtual_drive_id="239", …
```

Add alert rules for MegaRAID controller.

---

src/prometheus_alert_rules/lsi_sas_3.yaml
tests/unit/test_alert_rules/test_lsi_sas_3.yaml

Add the following alert rules for LSI SAS-3 controller.
- Sas3ircuCommandFailed
- LSISAS3ControllerNotFound
- LSISAS3IRVolumeNotFound
- LSISAS3IRVolumeUnhealthy
- LSISAS3PhysicalDiskUnhealthy
Tested with promtool and the test is included in the PR.
Almost identical to #5

Add alert rules for LSI SAS-3 controller

---

src/hw_tools.py
tests/unit/test_hw_tools.py

If the resource size is 0, then the installation won't be trigger.

feat(resource): Check resource size

---

lib/charms/grafana_agent/v0/cos_agent.py

The pydantic 2 migration is not available for cos_agent.
We will migrate to v2 after cos_agent support it.

build(pydantic): Pin pydantic under version 2

---

.github/workflows/pr.yaml

Functional test skipped because of timeout. Double the timeout to see if it works.

Increase functional test timeout.

---

config.yaml
src/charm.py
src/hardware.py
src/hw_tools.py
src/service.py
tests/functional/test_charm.py
tests/unit/test_charm.py
tests/unit/test_exporter.py
tests/unit/test_hardware.py
tests/unit/test_hw_tools.py

- The redfish host will be different for each machine and it shouldn't be provided by juju config
- Force user to use https protocol for RedFish.

fix(redfish-config): Get redfish host from ipmitool

---

templates/hardware-exporter-config.yaml.j2

These quotes are added to fix the pydantic error caused while reading the yaml file. If the quotes are absent for the redfish keys, the default value of empty string is registered as a None type while using safe_load and reading the yaml file in prometheus-hardware-exporter.
Fixes #43

Add quotes around keys in exporter config template

---

src/hw_tools.py
tests/functional/test_charm.py
tests/unit/test_hw_tools.py

`redfish.discover_ssdp` method is replaced with a simple login call to the redfish service. If the `RetriesExhaustedError` exception is raised, we can infer that the redfish service isn't present on the system.
This is done because the `redfish.discover_ssdp` method finds all the redfish services on the same network which is not what we want.
Fixes #61.

Replace redfish discover method

---

tests/functional/test_charm.py

The juju.model.deploy(bundle) command somehow cause error if the controller version is 3.1.6
---
Replace line
```python
ops_test.model.deploy(bundle)
```
with
```python
juju_cmd = ["deploy", "-m", ops_test.model_full_name, str(bundle)]
rc, stdout, stderr = await ops_test.juju(*juju_cmd)
```
[Reference](https://github.com/charmed-kubernetes/pytest-operator/blob/117350c3cee10dafdf42471b0d383392946bde14/README.md?plain=1#L76)

ci: Make CI compatible with juju controller 3.1.6

---

.github/workflows/check.yaml
tests/functional/conftest.py

Enable functional test with appropriate series

---

charmcraft.yaml

Since operator library assumes python >= 3.8 [1], this charm should not be installed on ubuntu bionic and below.
[1] https://github.com/canonical/operator/blob/2.2.0/setup.py#L75
Closes: #88

Drop bionic support

---

src/prometheus_alert_rules/ipmi_sensors.yaml
tests/unit/test_alert_rules/test_ipmi_sensors.yaml

Alert rule ipmi_generic_sensor_value ignoe type="Entity Presence"
Fix: #102

fix(alert): Ignore ipmi Entity Presence type alert

---

src/prometheus_alert_rules/general.yaml
tests/unit/test_alert_rules/test_general.yaml

Show be reviewed together with https://github.com/canonical/prometheus-hardware-exporter/pull/52

feat(alert): Add collector fail alert

---

metadata.yaml

docs: Update resource description.

---

tests/functional/test_charm.py
tests/unit/test_alert_rules/test_general.yaml

Relates to https://github.com/canonical/prometheus-hardware-exporter/pull/54

refactor: Fix alert rules for failed collector.

---

src/config.py
src/hw_tools.py
tests/unit/test_charm.py
tests/unit/test_exporter.py
tests/unit/test_hw_tools.py

Separate enabling logic of individual ipmi services monitoring

---

src/prometheus_alert_rules/redfish.yaml
tests/functional/requirements.txt
tests/unit/test_alert_rules/test_redfish.yaml

Add new alert rules with lower severity (warning) for when the health data isn't present and set with either "NA" or "N/A".
This prevents diluting the real critical health related alerts when the health data isn't available.
Resolves #113, #112, #129

feat: Add redfish alert rules for null health.

---

.github/workflows/check.yaml
Makefile
tests/unit/test_alert_rules/test_lsi_sas.yaml

This change adds another job in the `check.yaml` workflow to install the prometheus snap (which comes with promtool) and runs validation and unit tests on the alert rules using promtool.
Also fixes a typo in an alert rule test.
Resolves #3

feat: Add promtool testing in Makefile

---

src/charm.py
tests/functional/test_charm.py
tests/unit/test_charm.py

Fix failure functional test caused because of life-cycle changing.
- Config check be checked on update_status hook to avoid overwriting status.
- The exporter failed test doesn't make sense anymore because the exporter should able to auto-recover by itself. Change the logic to see if the exporter is able to auto-restart or not.
- Update error message validation.

test: Fix failed functional test

---

src/apt_helpers.py
src/hw_tools.py
tests/unit/test_apt_helpers.py
tests/unit/test_hw_tools.py

fix: apt install freeipmi-tools failed on focal

---

src/apt_helpers.py
src/charm.py
src/config.py
src/hardware.py
src/hw_tools.py
src/service.py
tests/unit/test_charm.py

Add `refresh_events` to `COSAgentProvider` to update relation data when
- config changed (default behavior)
- upgrade charm.

Add refresh_events to COSAgentProvider to update relation data

---

config.yaml
src/apt_helpers.py
src/charm.py
src/config.py
src/hardware.py
src/hw_tools.py
src/service.py
tests/unit/test_charm.py
tests/unit/test_exporter.py

Change default port for prometheus-exporter from 10000 to 10200 in order to avoid collisions with the same default port in juju-backup-all.
Fixes #133

fix: Change default port for prometheus exporter

---

src/charm.py
tests/unit/test_charm.py

As per suggestion in [this comment](https://github.com/canonical/hardware-observer-operator/pull/153#discussion_r1469370199).
Note: The default port is duplicated in both `src/charm.py` (in the `self.model.config.get` calls) and `config.yaml`. Technically, we just need one -- eg: provide default value in `config.yaml` and call `self.model.config.get` without any default. I'm leaving it as is for now.

refactor: Add constant for default exporter port

---

.github/workflows/check.yaml
requirements.txt

This will be used for triggering the workflow for the weekly scheduled tests.

Add workflow dispatch event to check.yaml

---

src/hw_tools.py
tests/unit/test_hw_tools.py

Allows for easier comprehension of the if statements that use this method. Extra details in docstring are also removed (this info can be provided elsewhere in the docs). Due to the change in vocabulary, the True/ False return conditions are also switched.
Unit tests are also modified.

refactor: Rename check_file_size

---

src/hw_tools.py
tests/unit/test_hw_tools.py

refactor: Split IPMIStrategy to sensor, sel, and dcmi strategies

---

src/charm.py
src/service.py
tests/unit/test_exporter.py

Also enable / disable the exporter service when starting and stopping the service. This could fix issues like the exporter unexpectedly stop / start when the machine is restart (or for any reasons like that).
Closes: #171

Enable / disable exporter service when start / stop the service.

---

tests/functional/conftest.py
tests/functional/requirements.txt
tests/functional/test_charm.py
tests/functional/utils.py

This PR is part of the effort to automate many of the manual tests for hardware observer. These tests depend on the availability of actual hardware resources. The tests are not meant to be run as part of CI but provide an easier way to validate functionality with real hardware whenever required, for example, before a new release.
The tests include:
* Check if provided collector is present in the exporter config file
* Verify if metrics are present at the expected endpoint on the unit
* Verify if collector specific metrics (as per the collectors being provided for the tests) are available in the metrics output
Collectors that need to be tested (as per availability on the underlying hardware) can be provided via the `--collectors` flag as space separated arguments. Eg: `--collectors …

feat: Add option to provide collectors for hardware dependent tests

---

src/charm.py
src/service.py
tests/unit/test_charm.py
tests/unit/test_exporter.py

Currently, `service.ExporterTemplate.render_config` determine `REDFISH_ENABLE` (jinja2) variable by  `get_hw_tool_white_list`, but the same information is also retrieved in `charm.HardwareObserverCharm._get_redfish_creds` via `bmc_hw_verifier`. If the two does not match (e.g. `bmc_hw_verifier` determines it redfish is not available but `get_hw_tool_white_list` determines that redfish is available), it will cause issue mentioned in #130.
This PR tries to remove the possibility that the two information is inconsistent by relying on single source of truth. Note, it might not solve #130, since the root cause is not clear, and it's not reproducible from my environement.

Improve dataflow when rendering config file.

---

tests/functional/bundle.yaml.j2
tests/functional/conftest.py
tests/functional/test_charm.py
tests/functional/utils.py

This patch modifies the `test_build_and_deploy` method to work even when testing with real hardware where the machine has already been pre-deployed in the model. The attaching of required resources after the bundle deployment is handled here as well.
The test execution logic has also been slightly tweaked. If the `--collectors` option is provided, then ONLY the real hardware dependent tests will be executed (marked with the "realhw" marker, belonging to `TestCharmWithHW`). If the option not provided, the hardware independent tests (in `TestCharm`) will be executed. If full tests are required, a make target can possibly be created which runs the pytest command with and without providing collectors.
Some logic has also been added to ensure that the `test_build_and_deploy` function will run …

tests: Modify deployment for real hw tests

---

src/prometheus_alert_rules/redfish.yaml
tests/unit/test_alert_rules/test_redfish.yaml

These cause a lot of alerts with no solutions. 
In some cases, it is expected for sensors to not have health info.
In other cases, where it may make sense to have the health info, there is nothing the operator can do if redfish itself isn't providing the Health info and providing `N/A`. So, the alert cannot be resolved.
Closes: #165

Remove Redfish HealthNotAvailable Alerts

---

tests/functional/requirements.txt
tests/functional/test_charm.py
tests/functional/utils.py
tox.ini

Adds collector specific tests most notably for redfish.
For the redfish test, two new env vars are introduced for the username and password credentials. After successful authentication to the redfish service, the redfish specific metrics are fetched.
Also fixes "ipmi_sensor" typo in `parse_metrics` function and `test_collector_specific_metrics_available`.
The documentation for letting the user know that they have to add these env vars for redfish will come as part of a later PR which will cover all prerequisite steps for real h/w testing.

tests: Collector specific tests for real hw

---

src/prometheus_alert_rules/redfish.yaml
tests/unit/test_alert_rules/test_redfish.yaml

Increase the duration before which redfish alerts get triggered. This prevents false alerts during ocassional flapping.
Fixes #146

fix(alerts): Increase duration before redfish alerts get triggered

---

requirements.txt

With https://github.com/canonical/hardware-observer-operator/pull/191, we are now not raising `ErrorStatus` directly and the unit tests have also been changed to reflect this.
This means that we can use the latest version of ops again.
Reverts change from [this commit](https://github.com/canonical/hardware-observer-operator/commit/a3002ee790d02bc9425dd18b1c6422f70d66693b).

chore: Remove pin on ops version

---

src/charm.py
tests/unit/test_charm.py

Fixes #190 
The `exporter.check_active` method being called in the `restart_exporter` method (from the update status event handler) will fail in case the exporter installation has not been done. This installation process takes place as part of the install event handler. 
The error happens because the `check_installed` function in `service.py` (called as a decorator for the various exporter service helper methods) would return `False` when the exporter isn't installed. This would cause all the Exporter class' methods in service.py (restart, check_active, check_health etc.) to return `False`. The issue occurs when the  `on_update_status()` --> `restart_exporter()` raises an exception when `exporter.check_active` consistently returns `False`. 
This PR removes the redfish credential …

fix: Remove redfish credential validation in install event handler

---

tests/functional/conftest.py
tests/functional/test_charm.py

Adds `test_redfish_credential_validation` which sets the redfish credentials and checks if the charm is funtioning as intended. This is necessary for hardware dependent tests since the charm only goes to active state once the correct redfish credentials are configured (assuming redfish is present on the underlying machine).  
`test_build_and_deploy` is broken up into smaller tests so that they are easier to manage. Also modifies logic in conftest.py so that all these tests are executed whether they're hw dependent or independent.
`test_redfish_metrics` has also been modified since we are setting the redfish credentials as part of the earlier test. The resource based tests (`test_resource_in_correct_location`, `test_wrong_resource_attached` and `test_resource_clean_up`) have been moved …

tests: Add hw dependent tests for redfish cred validation

---

tests/integration/test_cos_integration.py
tests/integration/utils.py

#199 , increases the duration of ipmi alerts, which caused the tests to fail because the alerts are in `Pending` state and not `Firing` for 5 minutes.  
This increases the retry time to 15 minutes, so that gives enough time for those alerts to be in `Firing` state.

Retry alerts to be fired for longer duration

---

src/hw_tools.py
tests/unit/test_hw_tools.py

Recreate the SDR cache if it's out of date, and hence the `ipmi-sel` and `ipmi-sensor` collectors won't be disabled, just because SDR cache was out of date.

Recreate sdr cache if it's out of date or invalid

---

src/charm.py
src/hw_tools.py
src/service.py
tests/unit/test_charm.py
tests/unit/test_exporter.py
tests/unit/test_hw_tools.py

The list will be created only once, during the install hook, and the same list will be reused everywhere else. This avoids generating a new list everytime it's needed, and potentially losing a hw from the list when it can't be temporarily accessed.
This way, the list of hardware being monitored is predictable.
This helps avoid issues like #202 
This also changes the 'white' list to 'enable' list. 
An action to refresh the hardware list will be provided as a future enhancement, so the operators can regenerate the hw tool list if needed. 
Setting the target as a dev  branch because this feature needs an accompanying action to regenerate hw list before it's merged to main.

Store hw tool list in _stored and reuse it.

---

config.yaml
src/charm.py
src/service.py
templates/hardware-exporter-config.yaml.j2
tests/functional/test_charm.py
tests/unit/test_charm.py
tests/unit/test_exporter.py

This change allows the user to manage the redfish client timeout using the existing `collect-timeout` charm config. When hardware exporter is installed, this configured value will be used for redfish (also refer [hardware-exporter config.py](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/config.py#L36) for config definition and [main.py](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/__main__.py#L186) where config is loaded from file).
Fixes #170

feat: Manage redfish client timeout with collect-timeout charm config

---

src/service.py
tests/functional/test_charm.py
tests/unit/test_exporter.py

Adds an extra `mode` parameter to the `_install` method that writes the config file so that we can restrict its read permissions.
Also removes unnecessary test numbers in a separate commit.

fix: Restrict read permissions for config file

---

config.yaml
requirements.txt
src/charm.py
src/config.py
src/exporter_helpers.py
src/hw_tools.py
src/service.py
tests/functional/conftest.py
tests/functional/requirements.txt
tests/functional/test_charm.py

Some refactor so that adding a new exporter becomes simpler. After this is merged, a new exporter can be added by implementing:
1.  a new `XxxExporter` class that inherits from `BaseExporter`.
2. Initialize the new exporter in charm init and append it to `self.exporters`. 
Unit tests will be updated and added after this is merged, the target is a dev branch.

Refactor to support multiple exporters

---

charmcraft.yaml
src/charm.py
src/hardware.py
src/hw_tools.py
tests/unit/test_charm.py

Redetect the hardwares and reinitialize the charm. The exporter service(s) will be reconfigured and restarted.

feat: redetect-hardwares juju action

---

src/charm.py

After operator framework fixes the incorrect types in `model.config` [1], it introduces some issues in our existing codebases since we used to assume them to have type of `str` which is not correct in the first place.
[1] https://github.com/canonical/operator/pull/1183

Fix typing issue

---

metadata.yaml
src/charm.py
tests/unit/test_exporter.py
tox.ini

The `metadata.yaml` support `limit` for interface, this can limits how many relation the interface can be connected to, and we can handle the relation checks in juju level.
Also removed the incorrect usage of `envdir` in `tox.ini` this is no longer working in `tox >= 4`.
Old behavior:
```shell
$ juju status
hardware-observer/1*  active    blocked            10.42.75.15            Cannot relate to more than one grafana-agent
```
New behavior:
```shell
$ juju relate g2  hardware-observer
ERROR cannot add relation "g2:cos-agent hardware-observer:cos-agent": establishing a new relation for hardware-observer:cos-agent would exceed its maximum relation limit of 1 (quota limit exceeded)
```
Closes: #144

refactor: remove multiple relation check in charm code.

---

src/prometheus_alert_rules/smart.yaml
tests/unit/test_alert_rules/test_smart.yaml

The discussion for this PR is in https://github.com/canonical/hardware-observer-operator/pull/238 but there was an issue with the merge over multiple commits to the dev branch. So I've consolidated the changes to one commit here and pushing it to main itself since it doesn't affect any other functionality.

Add alert rules for SMART metrics

---

tests/functional/test_charm.py

- Skip redfish related test `test_redfish_client_timeout_config` when redfish is unavailable.
- Upstream ops expects config values as strings, so the new `collect_timeout` is also set as string.

Skip redfish related test when redfish is unavailable

---

src/charm.py

Resolves #252 
The original issue is incorrect since the charm *will* go into blocked state if the exporter install fails. But the stored state variable that we use to track this might be misleading. So I've added a comment to make this clearer.

docs: Add comment for resource_installed

---

src/service.py
tests/unit/test_service.py

Override base render_config to render the service file.
This is because smartctl_exporter doesn't support providing config file.
The config options need to be provided as flags while exectuting
smartctl_exporter. So, the service file must be re-rendered when a config
value is changed.
Closes: #255

Re-render smartctl service file on config changed.

---

src/grafana_dashboards/BMC.json

Update line filter to use regex to match ipmiseld pid, the updated dashboard would no longer capture redundant logs:
Before:
After:
Closes https://github.com/canonical/hardware-observer-operator/issues/269

Update line filter for ipmiseld in BMC dashboard

---

src/service.py
tests/unit/test_service.py

Skip redfish validation if either username or password is missing
fix: #270

fix: redfish validation

---

tests/integration/test_cos_integration.py

COS Integration tests have been failing due to accessing traefik endpoint by public ip address, fix the test to use ip address that traefik is configured to serve on.
[Test](https://github.com/canonical/hardware-observer-operator/actions/runs/9948214345/job/27482345136) passed.
Fixes: https://github.com/canonical/hardware-observer-operator/issues/266

Fix integration test

---

src/charm.py
tests/unit/test_charm.py

Fixes: https://github.com/canonical/hardware-observer-operator/issues/284, https://github.com/canonical/hardware-observer-operator/issues/215
Issue https://github.com/canonical/hardware-observer-operator/issues/284 arises because there's no return statement following the defer() in the _on_config_changed event. When hardware-observer is deployed without a resource, the _on_config_changed event triggers, but no exporter gets installed. In the absence of a return statement, the function continues execution and may attempt to restart an exporter that hasn't been installed, which lead to a crash.
For the second fix mentioned in https://github.com/canonical/hardware-observer-operator/issues/215, the configuration is not rendered if the cos-agent relation is not provided. Considering this is a …

Clean up logic in `_on_config_changed` event

---

config.yaml
src/charm.py
src/hw_tools.py
src/service.py
tests/functional/test_charm.py
tests/unit/test_charm.py
tests/unit/test_hw_tools.py
tests/unit/test_service.py

- new charm config to disable redfish. With that, even that redfish is detected the user has the option to disable it.
- applied suggestions to change terminology. current_tools mean the ones already stored as cache.
- detected_available_tools run again (not cached) to detect new hardware
- changed redfish_conn_params to be a class property
- created new class property enabled_tools to remove detected tools that are disabled
- removed the possibility of redfish_conn_params_valid return None
Partially-Closes #282

Add config option to disable redfish

---

lib/charms/operator_libs_linux/v2/snap.py

This is just updating the snap lib for the future work that DCGM snap will require. Currently, the lib is not being used so it won't affect the charm and will result into less lines of change.
This is the result of running:
```
charmcraft fetch-lib charms.operator-libs-linux.v2.snap
```

Update the snap lib for the charm

---

metadata.yaml

Update docs for ARM and AMD resources:
- perccli and sas2ircu are not available for arm. We simply explain these resources are only available to AMD64 servers.
- storcli and sas3ircu support arm, updated the docs with relevant path.
- update storcli version in the description
superseded: #295 
depends on: #303

Update resource documentation

---

.github/workflows/check.yaml
.github/workflows/test_prometheus_rules.yaml

This is so we can update the check.yaml workflow
to the latest template from automation.

Move testing prometheus rules to separate workflow

---

charmcraft.yaml

Note: we cannot add functional tests for noble, because this is a subordinate charm and we don't have any other principle charms that support noble yet.
I did add functional tests for focal; they were missing from CI.

Add noble support

---

requirements-dev.txt

This is breaking to run lint on python 3.12 now that I'm on Noble.

Flake8 is pinned on version < 5 without apperently reasons

---

.github/workflows/cos_integration.yaml
tests/integration/requirements.txt

The Makefile was removed, so we must use tox directly here now.
Also rework the workflow and update the juju controller version to fix issues.

Fix integration tests (make -> tox)

---

src/service.py
tests/unit/test_service.py

Probably because of the usage of low level functions, as for example `os.open` and `os.fdopen`, it's harder to deal with buffering which can result into files with inconsistent content, which breaks the configuration and the hardware-exporter service.
After adding using high level functions and make the code simpler, the bug seems to be fixed
Closes: #305

Fix write_to_file function

---

.github/workflows/cos_integration.yaml

The cos_integration workflow should be triggered only by dispatch or, when the workflow was changed and not for all PR.
fixes: #344

Disable trigger of cos_integration in PR

---

src/hw_tools.py
tests/unit/test_hw_tools.py

The PR fixes some issues with the current Nvidia driver install logic:
- There is a check for nouveau drivers; if they are present, tell the operator. Otherwise, there is no point in installing Nvidia's closed-source drivers, as the Nvidia module slot is already occupied
-  Change the order of the arguments passed to `ubuntu-drivers`; see https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/2090502 - hilarious
- Run `modprobe` to load the installed drivers, ensuring a reboot is unnecessary. 
The changes were tested on a testflinger machine.
Closes: #361

Add nouveau check and modprobe to install

---

tests/functional/README.md
tests/functional/conftest.py
tests/functional/test_charm.py
tests/functional/utils.py
tox.ini

- Add a test to check if snaps are installed
- Fixes some bugs in the functional test suit
- Removes duplicate build step in the functional test (now the artifact build during the check workflow is used)
- Restructure the functional tests to represent the current logic involving `hardware-exporter.`
- Add a test to check if the charm manages to install the Nvidia drivers, if `--nvidia` flag is provided.
- Add a `--realhw` for the real hardware tests.
The hardware-independent tests were built assuming the `hardware-exporter` service and the config would still be rendered if no hardware was detected. This is not the case anymore, so it limits the number of tests we can run in the CI. But I've confirmed that the tests are passing on real hardware with the changes.
Closes: #351

Fix and restructure functional tests

---

src/charm.py

As noted in `get_stored_tools()`, StoredState cannot store arbitrary objects; this commit applies the same logic to `_on_redetect_hardware()`
Note: it would be nice to turn `stored_tools` into a property, but that requires a lot of unit test updates.
Fixes: #364

Store tools as a set of strings

---

src/prometheus_alert_rules/ssacli.yaml

Fire SsaCLIControllerNotOK only if status is not OK and not NOT CONFIGURED

---

src/prometheus_alert_rules/smart.yaml
tests/unit/test_alert_rules/test_smart.yaml

Only fire the alert if the `attribute_value_type="raw"` is set. The issue was in the fact that there are several entries for the attribute, which includes `value`, `worst` and `thresh`:
```
smartctl_device_attribute{attribute_flags_long="prefailure,updated_online,event_count,auto_keep", attribute_flags_short="PO--CK", attribute_id="5", attribute_name="Reallocated_Sector_Ct", attribute_value_type="raw", device="sda", instance="localhost:10201", job="hardware-observer_2_default", juju_application="hardware-observer", juju_model="hw-obs", juju_model_uuid="80a2c1d6-1a90-4ef0-8132-af698cf34f60", juju_unit="hardware-observer/1"}
0
smartctl_device_attribute{attribute_flags_long="prefailure,updated_online,event_count,auto_keep", attribute_flags_short="PO--CK", attribute_id="5", …
```

Fix SmartAttributeWarning alert

---

src/grafana_dashboards/smart.json

Fixes: #367
The bug occurs because the `instance` label is always set to `localhost:10201`. If you have multiple hosts, there might be duplicate drive names coming from different hosts; and because the label is not unique, there will be conflicts during the joins for some Smartctl graphs. So it's better to use the `juju_unit` label which is guaranteed to be unique.

Replace `instance` to `juju_unit` for the metric joins

---

src/hw_tools.py
tests/unit/test_hw_tools.py

If the sysadmin wants to pass the gpu to a virtual instance via pci
passthrough, they will need to make the gpu unavailable to the host
system by blacklisting the kernel driver. On such a system DCGM would
not be able to function and should therefore not be deployed.
This commit makes the NVIDIA gpu verifier more strict by only marking
DCGM as an available tool if both an NVIDIA gpu is detected *and* the
kernel module is not blacklisted.
Fixes: #362
Given a server with an NVIDIA gpu, drivers installed, and modules blacklisted via modprobe:
```
$ cat /etc/modprobe.d/blacklist-nvidia.conf 
blacklist nvidia
blacklist nvidiafb
blacklist nouveau
blacklist nvidia_drm
```
Following the `dev-environment.md` file, set up a local controller deploy an older stable charm (e.g. rev 84), setting up …

Don't install DCGM if the driver has been blacklisted

---

src/prometheus_alert_rules/ssacli.yaml
tests/unit/test_alert_rules/test_ssacli.yaml

Don't fire SsaCLIControllerNotOK if status is "NOT CONFIGURED"

---

src/hardware.py
src/hw_tools.py
src/service.py
tests/functional/test_charm.py
tests/unit/test_hardware.py
tests/unit/test_hw_tools.py
tests/unit/test_service.py

While we initially provided automatic installation of the NVIDIA driver
as a convenience, we then ran into the complexity of dealing with users
wanting to configure pci-passthrough and/or vgpu, and to possibly move
across these configurations post-deployment (see #362, #379).
After some more discussions, we agreed that deploying a gpu driver is
not the responsibility of hardware-observer, but rather of the principal charm
that needs to use the gpu (e.g. nova or kubernetes-worker).
This commit therefore drops the functionality of automatically
installing the driver and determining if it has been blacklisted for a
simpler workflow of installing DCGM only if a driver is found to have
been installed and loaded.
Fixes: #379

Stop managing the installation of the NVIDIA driver.

---

requirements.txt

Pin `urllib3 < 2.3.0` to support running on ubuntu@20.04 because the latest urllib3 does not support Python 3.8 anymore: https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#230-2024-12-22.
However, we should consider split the charm to build and run on the same environment.
Fix CI failure on ubuntu@20.04 base.

Pin urllib3 to support running on ubuntu@20.04

---

src/hw_tools.py
tests/unit/test_hw_tools.py

The snap service will be restarted at the config_changed event, so it's not necessary to restart in the strategy class.
Closes: #384

Avoid repeated restart DCGM snap service.

---

tests/functional/bundle.yaml.j2

grafana-agent on Noble is available for amd64 but not on arm64 yet.
Partially Closes: #347

Include the latest/stable channel for grafana-agent on Noble

---

tests/functional/README.md
tests/functional/bundle.yaml.j2
tests/functional/conftest.py
tests/functional/test_charm.py
tests/functional/utils.py

This commit attempts at fixing "realhw" functional tests, specifically for the following scenario:
```
tox -e func -- -v --realhw --model test --collectors ipmi_dcmi ipmi_sel ipmi_sensor --base ubuntu@22.04 --nvidia --keep-models
```
List of changes:
- Move rendering the bundle to a fixture and disable redfish if the collector isn't listed - this avoids tests complaining about incorrect redfish credentials when you're not interested in testing redfish anyway
- Update README to consider the work we did in dev-environment.md to be able to run tests on a single machine
- Fix incorrect hardware-exporter config search path

Fix realhw functests

---

metadata.yaml

#383 missed to change the right resource name now that we are targeting the 64 bit binary

Fix the instruction for adding sas3ircu resource

---

src/charm.py
tests/unit/test_charm.py

In a scenario where a machine does not have the hardware to install one exporter, we don't need to configure it on COS.
When it's not dinamic, grafana-agent might think that a target is down when actually the exporter is just not installed.
Fix: #287

Configure Prometheus scrape configuration dinamically

---

tests/functional/test_charm.py
tests/functional/utils.py

Closes #405 
Additionally, adds the following func tests:
- Check for DCGM and Smartctl Exporters metrics
- Check for config-changed for Smartctl Exporter port
- Check if the snaps for the above exporters are removed on uninstall

Func test fixes & improvements

---

src/hw_tools.py

Also see https://community.hpe.com/t5/operating-system-linux/linux-ubuntu-update-server-not-responding/m-p/7238924#M105438
Fixes: #414

Change protocol for HPE software repo from `http` to `https`

---

tests/manual/etc/1_add_machine/main.tf

I was running terraform in torchtusk using jammy. After cos was ready the job failed with:
> Unable to create integration, got error: cannot add relation
"grafana-agent:cos-agent hardware-observer:cos-agent": principal and subordinate applications' bases must match.
If base is not set, hwo deploys on noble and creates this issue. See the juju status
```
App                Version  Status   Scale  Charm              Channel        Rev  Exposed  Message
grafana-agent               active       1  grafana-agent      latest/stable  456  no       tracing: off
hardware-observer           blocked      0  hardware-observer  latest/stable  275  no       Missing relation: [cos-agent]
microk8s                    active       0  microk8s           1.28/stable    213  no       node is ready
ubuntu …
```

Add base for hwo charm on terraform

---

tests/manual/scripts/wait-for-model.sh

Traefik sometimes is taking more time than the default timeout. Increasing the default timeout solves the issue

Increase model wait time for terraform

---

.github/workflows/test_prometheus_rules.yaml
src/prometheus_alert_rules/general.yaml
tests/unit/test_alert_rules/test_general.yaml

Closes #438  
Increase the `for` duration of `CollectorFailed` alert from `1m` to `5m`. 
If real hardware issues occurs during that increased monitoring gap, HWO will still be able to detect them when monitoring resumes, given hardware metrics still immediately reflect the issue and barely no hardware failure resolves itself in minutes.
Also add a `keep_firing_for` duration to keep the alert firing to prevent flapping issue.
Update: `keep_firing_for` only supported from Prometheus 2.42+ which is newer than Prometheus snap in stable channel. Maybe use newer Prometheus, or remove it.
- [Charm Prometheus](https://charmhub.io/prometheus-k8s) uses the latest version of the [canonical/prometheus](https://ghcr.io/canonical/prometheus) image, which deploys Prometheus 2.46. 
- Remove …

CollectorFailed: Reduce check frequency

---

tests/functional/conftest.py
tests/functional/utils.py
tests/manual/jobs/eevee/README.md
tests/manual/jobs/kongfu/README.md
tests/manual/scripts/bootstrap.sh

- Fix some problems in realhw tests
- `hpe_ssa` collector is missing
- Add instruction on how to run realhw tests in `eevee` and `kongfu`

Enhance manual tests for `eevee` and `kongfu`

---

tests/manual/etc/3_deploy_cos/main.tf
tests/manual/etc/4_deploy_grafana_agent/main.tf

- Update juju terraform provider for cos & grafana-agent deployments to 0.20.0 to fix this error:
```
│ Error: Failed to query available provider packages
│ Could not retrieve the list of available versions for provider juju/juju:
│ no available releases match the given constraints ~> 0.17.0, 0.20.0
```
, from corresponding Sunbeam's commit: https://github.com/canonical/snap-openstack/commit/544fb29f4907b4997a7c37aabe16195ce3e94262
- Change some charm channels to `1/stable` instead of `latest/stable` to fix: 
```
| STDERR [etc/3_deploy_cos] terraform: │ Unable to create application, got error: selecting releases: charm or bundle not found for channel "latest/stable", base "amd64/ubuntu/20.04/stable"
```

Update some setting for manual tests

---

src/charm.py
tests/unit/test_charm.py

Fixes canonical/prometheus-hardware-exporter#102
As shown from the issue, the current `_scrape_config()` makes grafana-agent create a ghost job (`hardware-observer_0_default`) doing nothing, and the `collect-timeout` config is set to this job but not for other real jobs. So when a new `collect-timeout` is set, grafana-agent only updates `scrape_timeout` for the ghost job, and Prometheus will still give up scrapping after 10s (default by grafana-agent) for other real jobs. 
This fix removes the ghost job and add the scrape timeout for each job. The expected configuration will be:
```
scrape_configs:
- job_name: hardware-observer_0_default
metrics_path: /metrics
scrape_timeout: 50s
static_configs:
- labels:
juju_application: hardware-observer
juju_model: hw-obs
juju_model_uuid: …
```

Correct behavior when setting collect-timeout

---

.github/workflows/check.yaml
src/prometheus_alert_rules/ipmi_dcmi.yaml
src/prometheus_alert_rules/ipmi_sel.yaml
src/prometheus_alert_rules/ipmi_sensors.yaml
tests/unit/test_alert_rules/test_ipmi_dcmi.yaml
tests/unit/test_alert_rules/test_ipmi_sel.yaml
tests/unit/test_alert_rules/test_ipmi_sensors.yaml

Partially address https://github.com/canonical/prometheus-hardware-exporter/issues/101
Due to timeout issue, Prometheus may stop looking for the IPMI metrics before the exporter can export them, so these metrics won't appear in Prometheus. This PR adds rules checking whether the metric for IPMI commands has been exported (either the commands failed or success) to notify users in case IPMI metrics has disappeared for a while in Prometheus. 
If these alerts are firing, it could be a hint for the timeout issue, and probably increasing `collect-timeout` in charm config may help (already fixed in #455).

Add alert rules for missing IPMI metrics

---

lib/charms/grafana_agent/v0/cos_agent.py

This PR pulls in the newest version of the `cos-agent` library via `charmcraft fetch-lib`. Notably, this PR fixes a bug with faulty "default" scrape jobs being created by grafana-agent when hwo incorrectly detects hardware (see #459 for more context).
This PR shouldn't be breaking the hwo charm in any way, as it's just a minor patch library update :)

chore: update cos-agent charm lib to libpatch 22
