src/prometheus_alert_rules/ipmi_dcmi.yaml, src/prometheus_alert_rules/ipmi_sel.yaml, src/prometheus_alert_rules/ipmi_sensors.yaml, tests/unit/test_alert_rules/test_ipmi_dcmi.yaml, tests/unit/test_alert_rules/test_ipmi_sel.yaml, tests/unit/test_alert_rules/test_ipmi_sensors.yaml
Alert rules for ipmi sel, ipmi dcmi and ipmi sensor metrics.
=> Add alert rules based on IPMI data

src/prometheus_alert_rules/mega_raid.yaml, tests/unit/test_alert_rules/test_mega_raid.yaml
Update alert rule for MegaRAID collector according to the [PR](https://github.com/canonical/prometheus-hardware-exporter/pull/6)
Depends: [PR](https://github.com/canonical/prometheus-hardware-exporter/pull/6)
=> Update alert rule for mega raid collector.

src/prometheus_alert_rules/perccli.yaml, tests/unit/test_alert_rules/test_perccli.yaml
=> feat(alert): Add alert rule for perccli

src/charm.py, src/config.py, src/vendor.py, tests/unit/test_charm.py, tests/unit/test_vendor.py
It's a example how to define the strategy for different 3rd party tool resources.
- Refactor: Change InstallStrategy to Strategy
- Feature: Add remove strategy for storcli.
- Feature: Change install strategy for storcli.
=> feat(strategy): Add remove strategy and small refactor

src/charm.py, src/config.py, src/hardware.py, src/hw_tools.py, tests/unit/test_charm.py, tests/unit/test_exporter.py, tests/unit/test_hardware.py, tests/unit/test_hw_tools.py
- hardware-verifier for
- perccli
- sas2ircu
- sas3ircu
- storcli
- megacli
- Refactor VendorXXX to HWToolXXX
- Refactor the config of hardware to use Enum instead of string.
=> feat: hardware-verifier

src/hw_tools.py, tests/unit/test_hw_tools.py
- Small fix to ensure lshw output is dict not list.
=> fix(lshw): lshw's default output should be a dict not list

requirements.txt, src/config.py, src/hw_tools.py, tests/unit/test_hw_tools.py
- Add strategy for redfish
- enable redfish though the exporter config(need to verify the config value)
- Change name ipmi_hw_verifier to bmc_hw_verifier and add check for redfish
=> feat(redfish): Add strategy for redfish

config.yaml, src/charm.py, src/service.py, tests/functional/bundle.yaml.j2, tests/functional/conftest.py, tests/functional/test_charm.py, tests/unit/test_charm.py, tests/unit/test_exporter.py
Add basic functional testing for the charm.
=> Improve functest

tests/functional/conftest.py, tests/functional/test_charm.py
We can choose either #35  or this PR
=> test: Make functional test workable on juju 2

requirements.txt, src/service.py, templates/hardware-exporter-config.yaml.j2, tests/functional/test_charm.py, tests/unit/test_exporter.py
- Fix wrong redfish config
- Remove redfish-utilities from requirement
=> fix: integrate-redfish

README.md
Add badges which show the revision on Charmhub and the status of the `release.yaml` GitHub actions workflow.
=> Add CI badges for Charmhub

src/hardware.py, tests/unit/test_hardware.py
lshw has different outputs on different ubuntu series
Fix: #42
=> fix(lshw): Fix different lshw output issue

docs/resources.md, metadata.yaml
=> Update storCLI resource download link

src/prometheus_alert_rules/redfish.yaml, tests/unit/test_alert_rules/test_redfish.yaml
Also add unit tests for alert rules.
=> Add redfish alert rules

lib/charms/grafana_agent/v0/cos_agent.py
for hardware-observer to be able to coexist with a principal that **also** implements `cos_agent`, a new version of the cos_agent library is needed. this pr solves that.
=> bump charm library for cos agent

metadata.yaml
=> add github link to charmhub

tests/functional/test_charm.py
ops_test.fast_forward() temporarily speeds up the update-status firing rate. This is effectively equal to setting and resetting the "update-status-hook-interval" model config before and after the relevant code.
Previously, we would have had to spend 5m waiting for the unit status change to be detected after any state change to the hardware-exporter systemd service.
Refer: https://github.com/charmed-kubernetes/pytest-operator/blob/main/docs/reference.md#async-def-fast_forwardself-fast_interval-str--10s-slow_interval-optionalstr--none
=> Speed up functional tests with ops_test.fast_forward()

src/hw_tools.py, tests/unit/test_hw_tools.py
=> Catch `ServerDownOrUnreachableError` in redfish_available function

src/prometheus_alert_rules/ipmi_dcmi.yaml, tests/unit/test_alert_rules/test_ipmi_dcmi.yaml
Change alert IPMIDCMIPowerConsumptionOutstanding to IPMIDCMIPowerConsumptionPercentageOutstanding
Should merge together with https://github.com/canonical/prometheus-hardware-exporter/pull/45
=> fix(alert): Add alert IPMIDCMIPowerConsumptionPercentageOutstanding

src/checksum.py
=> fix: Add sas3ircu checksum for P16

src/hardware.py, src/hw_tools.py, tests/unit/test_hardware.py, tests/unit/test_hw_tools.py
Fetch hardware information from hwinfo and add support items
Fix: #90
=> fix: support smart array

lib/charms/operator_libs_linux/v1/systemd.py
See PR description. 
The new version of operator libs linux introduce `service_enable`, `service_disable` and more. Those feature is required for #171
=> chore: Bump charm library for operator libs linux to v1.4

tests/functional/test_charm.py
**NOTE: This requires https://github.com/canonical/hardware-observer-operator/pull/179 to be merged first**
Resource related functionality being tested includes:
* Error message, blocked status if required resource is not attached
* Check if resource is installed to correct location
* Error message, blocked status if wrong resource is attached
* Resource clean up is working
=> tests: Add resource tests for real hw

tests/functional/README.md
Check [this link](https://github.com/dashmage/hardware-observer-operator/blob/bseng-2067-documentation/tests/functional/README.md) to see the formatted README page.
=> docs: Add steps for testing with real hw

.github/workflows/cos_integration.yaml, Makefile, tests/integration/requirements.txt, tests/integration/test_cos_integration.py
* Setup lxd and microk8s controllers
* Run the integration tests on top of those controllers
* After this is merged, it can be added as part of the weekly tests.
=> Add workflow for cos integration tests

src/prometheus_alert_rules/ipmi_dcmi.yaml, src/prometheus_alert_rules/ipmi_sel.yaml, src/prometheus_alert_rules/ipmi_sensors.yaml, tests/unit/test_alert_rules/test_ipmi_dcmi.yaml, tests/unit/test_alert_rules/test_ipmi_sel.yaml, tests/unit/test_alert_rules/test_ipmi_sensors.yaml
=> fix(alerts): Increase duration before which ipmi alerts get triggered

.github/workflows/check.yaml, Makefile, tox.ini
Update juju channel to 3.4, add concurrency.
=> Support juju 3.4

src/apt_helpers.py, src/hw_tools.py
=> Fix typos in the comments.

config.yaml, requirements.txt, src/charm.py, src/config.py, src/exporter_helpers.py, src/hw_tools.py, src/service.py, tests/functional/conftest.py, tests/functional/requirements.txt, tests/functional/test_charm.py, tests/unit/test_service.py
This can directly be merged. More changes need to be made before merging to main branch.
=> Dev: Update on refactor to support multiple exporters

templates/smartctl-exporter.service.j2
=> Fix: Use correct flag to specify port for smartctl exporter

README.md
Update README to include smartctl integration
=> Update README for smartctl exporter integration

.github/workflows/check.yaml, charmcraft.yaml, tests/functional/conftest.py, tests/functional/test_charm.py
- Fix issue #314, missing testing model on crashdump
- Add arm64 functional test
- Add arm64 charm build
=> ci:  arm64 support

src/charm.py, tests/unit/test_service.py
=> Fix typos accept_* -> assert_*

.github/workflows/cos_integration.yaml
See https://github.com/canonical/hardware-observer-operator/pull/345 for background.
=> Document the purpose of cos integration workflow

src/grafana_dashboards/GPU.json
=> Fix incorrect datasource for the GPU dashboard

requirements.txt
Reverts canonical/hardware-observer-operator#385 and closes #397
=> Revert "Pin urllib3 to support running on ubuntu@20.04"

lib/charms/operator_libs_linux/v0/apt.py
This addressed another issue found in https://github.com/canonical/hardware-observer-operator/issues/414#issuecomment-2765326045
=> Bump operator_libs_linux.v0.apt from v11 to v17

charmcraft.yaml, requirements-dev.txt, requirements.txt
Install the following package from binary
- cosl
- pydantic
- prometheus-hardware-exporter
Related to https://github.com/canonical/charmcraft/issues/2259 (see comments for the root cause)
=> Don't build some packages from source

charmcraft.yaml, requirements-dev.txt, requirements.txt
This reverts commit f939dc6cda17b5dc895bbf1fcc7ee242c235357a.
=> Revert "Don't build some packages from source (#429)"

src/prometheus_alert_rules/ipmi_sel.yaml, tests/unit/test_alert_rules/test_ipmi_sel.yaml
The changes is a result of the re-design of ipmi-sel collector PR:  https://github.com/canonical/prometheus-hardware-exporter/pull/99
=> Update alert rules
